### ISSUE TITLE
Issue with youtube streaming on ipv6

### ISSUE THREAD

**Issue by Foexy** [popcorner/cernet-ipv6-hosts#2]
IPV6 Host file works but in china youtube and facebook browsing is perfect but there are some streaming issues. 
Youtube does not stream videos.
Facebook does not load images and videos. 

Can you help me in this regard?
How to fix this.

**Comment by popcorner** [comment]
Youtube video is not supported in this hosts file, because it has too many domain names and need to add more than 20,000 lines. This is just a lightweight hosts file.
Some of the facebook image ip are blocked in CERNET this year, so you may not see the images. You can load images when facebook allocate another domain name with an ip address that can be connected via CERNET for you. This repo will update new IPs if they are able to be connected.
